import type { Review } from '@/types'

function calcRating(cr: Review['categoryRatings']): number {
  const scores = [
    cr.paymentContracts,
    cr.communication,
    cr.deliveryQuality,
    cr.reliability,
    cr.wouldWorkAgain ? 5 : 1,
  ]
  return Math.round((scores.reduce((a, b) => a + b, 0) / 5) * 10) / 10
}

const SEED: Review[] = [

  // ── Salesforce ────────────────────────────────────────────────────────────
  {
    id: 'sf-01',
    company: 'Salesforce',
    category: 'CRM / Enterprise Software',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'Powerful platform, but implementation was a 9-month ordeal',
    content: 'We migrated our entire sales org to Salesforce after being told the implementation would take three months. It took nine. Every scope change was billed at full professional-services rates, and the original project manager was replaced twice mid-engagement. The platform itself is genuinely capable once configured correctly, SOQL-based reporting is best-in-class, but the gap between what sales promises and what delivery delivers is enormous. We would not sign a multi-year deal again without fixed-scope protections in the contract.',
    pros: 'Deep AppExchange ecosystem, unmatched reporting once you know SOQL, large talent pool familiar with the platform.',
    cons: 'Implementation timelines are routinely underestimated. Licensing costs escalate aggressively at renewal. Support tier required for real answers costs extra.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-03-14').toISOString(),
    reviewerHash: 'anon_4a8b1c2d',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@sf-01',
    upvotes: 41,
    isVerified: true,
  },
  {
    id: 'sf-02',
    company: 'Salesforce',
    category: 'CRM / Enterprise Software',
    rating: calcRating({ paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'Best-in-class reporting once you get past the learning curve',
    content: 'Our revenue operations team runs entirely on Salesforce and after two years of investment in configuration and training, I would not switch. The reporting engine is genuinely sophisticated, we built dashboards in SFDC that replaced three separate BI tools. The learning curve is steep and the licensing model is aggressive, but for a mid-market B2B SaaS company this is the right platform. Renewal negotiation requires preparation, but we got a fair deal by coming in with competitive quotes.',
    pros: 'Reporting and dashboards are unmatched. Large ecosystem of trained admins and developers. Integrates with everything.',
    cons: 'Expensive at scale. Requires a dedicated admin to run effectively. Renewal pricing is aggressive without leverage.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-08-22').toISOString(),
    reviewerHash: 'anon_9f3e7a12',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@sf-02',
    upvotes: 33,
    isVerified: true,
  },
  {
    id: 'sf-03',
    company: 'Salesforce',
    category: 'CRM / Enterprise Software',
    rating: calcRating({ paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'Partner programme exists on paper, deal registration is ignored',
    content: 'As an ISV partner we were told deal registration would protect our accounts from the direct sales team. In practice, the direct AEs work the same accounts independently and the partner team has no authority to enforce anything. We lost three registered deals in twelve months to direct Salesforce sales, and each dispute resolution took weeks with no outcome in our favour. The Trailhead programme and Marketplace give real access to customers, but the economics of the partnership are stacked firmly against ISVs.',
    pros: 'Large customer base to sell into. Trailhead certifications carry real market credibility. Marketplace installs convert well.',
    cons: 'Deal registration offers no real protection. Direct team actively competes with partners. MDF reimbursements take 90+ days.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-11-05').toISOString(),
    reviewerHash: 'anon_b7d5e3f1',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@sf-03',
    upvotes: 58,
    isVerified: true,
  },
  {
    id: 'sf-04',
    company: 'Salesforce',
    category: 'CRM / Enterprise Software',
    rating: calcRating({ paymentContracts: 4, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'Strong engineering culture that still survives the acquisition machine',
    content: 'I joined Salesforce as a senior engineer three years ago and have stayed because the technical environment is genuinely excellent. The codebase is mature, the infrastructure investment is serious, and the engineering managers I have worked under have shielded the team from the worst of the corporate churn. Compensation is competitive and the internal mobility programme is real. The communication from upper leadership around strategy has become notably more opaque in the last 18 months, the volume of acquisitions makes it hard to understand where individual product lines are going.',
    pros: 'Strong engineering practices and infrastructure. Competitive compensation. Real internal mobility across product orgs.',
    cons: 'Frequent reorgs from acquisitions disrupt long-term planning. Leadership communication has become vaguer. Performance review process is too tied to stack ranking.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 4, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2026-01-17').toISOString(),
    reviewerHash: 'anon_c2e0g8i6',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@sf-04',
    upvotes: 27,
    isVerified: true,
  },
  {
    id: 'sf-05',
    company: 'Salesforce',
    category: 'CRM / Enterprise Software',
    rating: calcRating({ paymentContracts: 4, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false }),
    title: 'Procurement was professional but the engagement dropped off after contract signing',
    content: 'We contracted Salesforce professional services to build a custom CPQ configuration for our pricing team. The pre-sales process was thorough and the commercial terms were fair, payments were on time and the contract was clearly written. However, the quality of the engagement declined significantly after contract execution. The lead consultant assigned at the start was replaced partway through, and the handover was incomplete. The final deliverable worked, but it was underdocumented and we have spent considerable internal engineering time filling the gaps.',
    pros: 'Professional pre-sales process. Contract terms were fair. Payments processed correctly.',
    cons: 'Engagement quality dropped after contract signing. Consultant turnover mid-project hurt continuity. Deliverable documentation was insufficient for our team to maintain independently.',
    relationshipType: 'Vendor',
    categoryRatings: { paymentContracts: 4, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2026-04-03').toISOString(),
    reviewerHash: 'anon_d4f2h0j8',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@sf-05',
    upvotes: 19,
    isVerified: true,
  },

  // ── HubSpot ───────────────────────────────────────────────────────────────
  {
    id: 'hs-01',
    company: 'HubSpot',
    category: 'CRM / Marketing Automation',
    rating: calcRating({ paymentContracts: 4, communication: 5, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'The best CRM for scaling SMBs, onboarding alone was worth the price',
    content: 'We evaluated HubSpot against Salesforce and Pipedrive when we hit 30 employees and chose HubSpot for its breadth and ease of use. The onboarding team was genuinely excellent, responsive, knowledgeable, and they adapted their process to our sales motion rather than forcing us into a template. The CRM, Marketing Hub, and Service Hub integration is seamless in a way that Salesforce add-ons never quite manage. Two years in and our sales team adoption rate is over 90%, which speaks for itself.',
    pros: 'Exceptional onboarding support. Seamless CRM and marketing integration. High sales team adoption due to clean UX.',
    cons: 'Pricing scales steeply as contacts grow. Some marketing automation features require the Professional tier unnecessarily.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 4, communication: 5, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-02-11').toISOString(),
    reviewerHash: 'anon_e5g3i1k9',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@hs-01',
    upvotes: 62,
    isVerified: true,
  },
  {
    id: 'hs-02',
    company: 'HubSpot',
    category: 'CRM / Marketing Automation',
    rating: calcRating({ paymentContracts: 2, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'Freemium hooks you in, then the pricing walls hit hard',
    content: 'HubSpot is genuinely good product, our marketing team loves the workflow builder and the CRM is intuitive. The problem is the pricing model, which is designed to get you dependent before revealing the real cost. We started on the free tier, upgraded to Starter because we needed basic features like email sequences, then discovered most of what we actually needed was behind the Professional tier. The jump from Starter to Professional is $400/month per hub. By the time we fully understood the true cost of what we needed, we were too embedded to move.',
    pros: 'Clean UX that non-technical marketers can use. Workflow automation is genuinely powerful. Free tier is useful for evaluating.',
    cons: 'Pricing tiers are structured to maximise upsells. Key features artificially gated behind expensive tiers. Contract renewal included a 15% price increase without notice.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 2, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-06-30').toISOString(),
    reviewerHash: 'anon_f6h4j2l0',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@hs-02',
    upvotes: 89,
    isVerified: true,
  },
  {
    id: 'hs-03',
    company: 'HubSpot',
    category: 'CRM / Marketing Automation',
    rating: calcRating({ paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true }),
    title: 'Solutions partner programme has real revenue, but take the SLA promises with salt',
    content: 'We are a HubSpot Solutions Partner and have built a significant portion of our agency revenue on it. The partner team is responsive, the co-marketing budget is real, and customer referrals from the marketplace have been a genuine pipeline driver. My one caution is around the partner SLAs, when things go wrong with a client account, escalation times are longer than advertised and the resolution often requires us to do the diagnostic work ourselves. The partner portal has also been rebuilt twice in three years with no improvement in the ticket resolution features.',
    pros: 'Customer referrals from marketplace are genuine. Partner team is accessible and supportive. Co-marketing budget is real and usable.',
    cons: 'Escalation SLAs for partner support are not reliably met. Partner portal rebuilds have not improved core functionality. Certification requirements increase each year.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2025-10-18').toISOString(),
    reviewerHash: 'anon_g7i5k3m1',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@hs-03',
    upvotes: 34,
    isVerified: true,
  },
  {
    id: 'hs-04',
    company: 'HubSpot',
    category: 'CRM / Marketing Automation',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false }),
    title: 'Grow-at-all-costs culture is burning people out at every level',
    content: 'I spent two years in HubSpot marketing and left because the pace was genuinely unsustainable. The company culture materials say all the right things about employee wellbeing, but the reality is a relentless quarterly pressure that trickles down to every team. Manager quality varies wildly, I had one exceptional manager followed by one who had clearly been promoted for hitting numbers, not for knowing how to develop people. Compensation is competitive, and the product genuinely is good, but I would not recommend the experience to someone who values stability.',
    pros: 'Competitive base salary and equity. Strong product to work on, you believe in what you are selling. Good remote flexibility.',
    cons: 'Quarterly growth pressure creates an unsustainable pace. Manager quality is inconsistent. Headcount reductions were handled poorly with little transparency.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2026-02-25').toISOString(),
    reviewerHash: 'anon_h8j6l4n2',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@hs-04',
    upvotes: 71,
    isVerified: true,
  },
  {
    id: 'hs-05',
    company: 'HubSpot',
    category: 'CRM / Marketing Automation',
    rating: calcRating({ paymentContracts: 4, communication: 4, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true }),
    title: 'Integration support was responsive and the contract terms were vendor-friendly',
    content: 'We built a data integration between our platform and HubSpot for a joint customer. The HubSpot developer relations team was genuinely helpful, they responded to API questions within 24 hours consistently and the documentation is among the best I have seen from any SaaS vendor. Contract terms for the technology partnership were fair, with clear IP provisions and payment on the agreed schedule. The integration certification process added unexpected time, but the team communicated delays proactively rather than leaving us in the dark.',
    pros: 'Excellent developer documentation. Responsive developer relations team. Fair contract terms with clear IP provisions.',
    cons: 'Integration certification process is slower than advertised. Some API rate limits are underdocumented and hit us in production.',
    relationshipType: 'Vendor',
    categoryRatings: { paymentContracts: 4, communication: 4, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2026-04-14').toISOString(),
    reviewerHash: 'anon_i9k7m5o3',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@hs-05',
    upvotes: 22,
    isVerified: true,
  },

  // ── AWS ───────────────────────────────────────────────────────────────────
  {
    id: 'aws-01',
    company: 'AWS',
    category: 'Cloud Infrastructure',
    rating: calcRating({ paymentContracts: 4, communication: 3, deliveryQuality: 5, reliability: 5, wouldWorkAgain: true }),
    title: 'Reliability is genuinely unmatched, pricing is an engineering problem in itself',
    content: 'We have run production workloads on AWS for four years across fifteen services and the reliability record is exceptional. In that time we have experienced one regional incident that materially affected us, and the post-incident communication from AWS was thorough and honest. The infrastructure is simply the best available at any price point. The challenge is cost management, AWS pricing is extraordinarily complex and without a dedicated FinOps function you will overspend significantly. The free tier and spot instance economics are genuinely powerful once you invest in understanding them.',
    pros: 'Industry-leading reliability with 99.99%+ SLAs that are actually met. Breadth of services covers every infrastructure need. Strong compliance and security certifications.',
    cons: 'Pricing complexity requires dedicated FinOps expertise. Surprise bills from data egress and misunderstood pricing are common. Support is tier-gated, Developer support is inadequate for production issues.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 4, communication: 3, deliveryQuality: 5, reliability: 5, wouldWorkAgain: true },
    timestamp: new Date('2025-01-28').toISOString(),
    reviewerHash: 'anon_j0l8n6p4',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@aws-01',
    upvotes: 94,
    isVerified: true,
  },
  {
    id: 'aws-02',
    company: 'AWS',
    category: 'Cloud Infrastructure',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 5, reliability: 4, wouldWorkAgain: false }),
    title: 'Support tiers are engineered to upsell, not to solve your problems',
    content: 'The infrastructure is world-class, but the support model is deliberately tiered in a way that makes real help inaccessible unless you pay for Business or Enterprise support. We had a production issue with an RDS instance that took four hours to resolve because our Developer support tier had no access to an engineer, just documentation links and a 24-hour response window. The engineering was fine. The product is exceptional. But when something goes wrong at 2am, AWS support will not save you unless you pay $15,000/month for the privilege.',
    pros: 'Infrastructure reliability and performance are best-in-class. Service breadth means you rarely need to leave the AWS ecosystem.',
    cons: 'Support tier required for real help is very expensive. Response times on lower tiers are unacceptable for production workloads. Cost visibility requires third-party tooling.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 5, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-05-15').toISOString(),
    reviewerHash: 'anon_k1m9o7q5',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@aws-02',
    upvotes: 107,
    isVerified: true,
  },
  {
    id: 'aws-03',
    company: 'AWS',
    category: 'Cloud Infrastructure',
    rating: calcRating({ paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'ISV Partner Programme accelerated our pipeline meaningfully',
    content: 'We joined the AWS ISV Accelerate programme two years ago and it has materially changed our go-to-market. Co-sell motions with AWS AEs have closed deals we would never have sourced independently, and the Marketplace listing has created an inbound channel that we did not previously have. The Partner Development Manager we work with is responsive and genuinely invested in our success. The programme requires significant internal investment, AWS certifications, Marketplace listing work, co-sell process compliance, but for an infrastructure-adjacent SaaS company the ROI is real.',
    pros: 'Co-sell motions with AWS AEs close deals that would otherwise be out of reach. Marketplace listing creates genuine inbound pipeline. PDM support is responsive and knowledgeable.',
    cons: 'Programme requires significant internal investment to maintain. Certification and compliance requirements increase each year. Some co-sell AEs are more engaged than others.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-09-07').toISOString(),
    reviewerHash: 'anon_l2n0p8r6',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@aws-03',
    upvotes: 48,
    isVerified: true,
  },
  {
    id: 'aws-04',
    company: 'AWS',
    category: 'Cloud Infrastructure',
    rating: calcRating({ paymentContracts: 5, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'The best career launch pad in the industry, if you can handle the pace',
    content: 'I spent three years as a Solutions Architect at AWS and left to found my own company, which is itself a testament to the quality of the education you receive. The training programme is rigorous, the internal tooling is unlike anything outside of the big tech companies, and the customer exposure at breadth is unmatched. Compensation is top-quartile. The pace is intense and the on-call culture in some service teams is brutal, but the baseline technical standard you come away with is exceptional. I would do it again.',
    pros: 'Exceptional technical training and breadth of exposure. Top-quartile compensation. Strong alumni network and brand recognition.',
    cons: 'On-call culture in infrastructure teams is intense. Internal bureaucracy for headcount and tooling decisions is significant. Pace of change is relentless and can be exhausting.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 5, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-12-20').toISOString(),
    reviewerHash: 'anon_m3o1q9s7',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@aws-04',
    upvotes: 55,
    isVerified: true,
  },
  {
    id: 'aws-05',
    company: 'AWS',
    category: 'Cloud Infrastructure',
    rating: calcRating({ paymentContracts: 2, communication: 2, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'A billing surprise almost ended our startup, AWS owes better cost guardrails',
    content: 'We accidentally left a NAT gateway running in a staging environment for three months. The bill was $12,000. AWS has no default spending alerts, no automatic shutoff, and their billing UI makes it extremely hard to trace which service is generating which cost in real time. When we contacted support to dispute the charges, the response was a policy document and a small one-time credit. The infrastructure itself worked perfectly. But AWS is designed to maximise spend from confused or inattentive users and the guardrails are opt-in, obscure, and insufficient for startups.',
    pros: 'Infrastructure reliability and performance are excellent. Spot instances offer significant cost savings if you know how to use them.',
    cons: 'Billing is deliberately complex with minimal default protection against runaway costs. Dispute resolution for billing errors is slow and unsympathetic. Cost management requires third-party tooling.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 2, communication: 2, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2026-03-12').toISOString(),
    reviewerHash: 'anon_n4p2r0t8',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@aws-05',
    upvotes: 136,
    isVerified: true,
  },

  // ── Stripe ────────────────────────────────────────────────────────────────
  {
    id: 'str-01',
    company: 'Stripe',
    category: 'Payments / Fintech',
    rating: calcRating({ paymentContracts: 5, communication: 4, deliveryQuality: 5, reliability: 4, wouldWorkAgain: true }),
    title: 'The best payment infrastructure on the market, the developer experience alone justifies it',
    content: 'We have processed over $40M through Stripe across two products and would not consider switching. The API documentation is the clearest I have encountered from any infrastructure provider. Integration time for a full checkout flow with webhooks and subscription management was three days for a mid-level engineer. Fraud rates have dropped since we moved from our previous processor. The pricing is not the cheapest, but the reduction in engineering overhead and the reliability record make the total cost lower than the alternatives.',
    pros: 'Best-in-class API documentation and developer experience. Reliable fraud detection with Radar. Excellent webhook infrastructure.',
    cons: 'Per-transaction pricing adds up at volume, worth negotiating Enterprise rates above $1M/year. Stripe support response times can be slow for non-critical issues.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 5, communication: 4, deliveryQuality: 5, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-04-09').toISOString(),
    reviewerHash: 'anon_o5q3s1u9',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@str-01',
    upvotes: 83,
    isVerified: true,
  },
  {
    id: 'str-02',
    company: 'Stripe',
    category: 'Payments / Fintech',
    rating: calcRating({ paymentContracts: 4, communication: 3, deliveryQuality: 5, reliability: 4, wouldWorkAgain: true }),
    title: 'Developer experience exceptional, support is a weak point at scale',
    content: 'Stripe is the right choice for any technical team building a payments product. The API is elegant, the testing environment is thorough, and features like Connect and Billing have allowed us to build subscription and marketplace flows that would have taken months to build on our own. Where Stripe falls short is support once you have a complex setup. Generic support agents work from playbooks and escalation to a specialist can take days. For a product where payment failures directly affect revenue, this is a meaningful gap.',
    pros: 'Stripe Connect and Billing dramatically reduce custom development time. Testing environment is comprehensive. Dashboard analytics are useful for non-technical stakeholders.',
    cons: 'Support escalation to a specialist is slow for complex issues. Chargeback dispute interface is cumbersome. Documentation for edge cases in Connect can be hard to find.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 4, communication: 3, deliveryQuality: 5, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-07-23').toISOString(),
    reviewerHash: 'anon_p6r4t2v0',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@str-02',
    upvotes: 47,
    isVerified: true,
  },
  {
    id: 'str-03',
    company: 'Stripe',
    category: 'Payments / Fintech',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true }),
    title: 'Stripe Atlas helped us incorporate quickly but came with unexpected complexity',
    content: 'We used Stripe Atlas to incorporate a Delaware C-Corp from outside the United States. The process itself was faster than doing it directly and the Stripe team answered our questions promptly throughout. However the Atlas package comes with a set of partner introductions, accounting, legal, banking, that are presented as seamless but each relationship requires significant independent evaluation. Two of the three recommended partners were not the right fit for our stage. Atlas is a good starting point but not the turnkey solution the marketing suggests.',
    pros: 'Fast Delaware incorporation process. Stripe team is responsive during the Atlas journey. Banking setup is genuinely streamlined.',
    cons: 'Partner recommendations need independent evaluation, they are referrals, not endorsements. Ongoing compliance requirements are not fully explained upfront. More expensive than direct incorporation at scale.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2025-11-14').toISOString(),
    reviewerHash: 'anon_q7s5u3w1',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@str-03',
    upvotes: 29,
    isVerified: true,
  },
  {
    id: 'str-04',
    company: 'Stripe',
    category: 'Payments / Fintech',
    rating: calcRating({ paymentContracts: 4, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false }),
    title: 'Move fast culture produces excellent products but burns through people',
    content: 'I worked at Stripe for eighteen months as a product manager and left because the pace was simply not compatible with the rest of my life. The product quality and engineering rigour are genuinely exceptional, I learned more in those eighteen months than in the previous four years combined. But the expectation is that work is the primary commitment and everything else is secondary. Compensation is top-of-market, which is how they attract people willing to accept those conditions. The culture is intellectually exciting and professionally demanding in equal measure.',
    pros: 'World-class engineering and product colleagues. Exceptional compensation. Fast learning environment with real product impact.',
    cons: 'Work-life balance is a low priority in practice. The intensity is unsustainable for most people beyond two to three years. Feedback culture can be harsh if you are not prepared for it.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 4, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2026-01-30').toISOString(),
    reviewerHash: 'anon_r8t6v4x2',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@str-04',
    upvotes: 44,
    isVerified: true,
  },
  {
    id: 'str-05',
    company: 'Stripe',
    category: 'Payments / Fintech',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 5, reliability: 5, wouldWorkAgain: false }),
    title: 'Chargeback handling process is opaque and consistently favours the buyer',
    content: 'Stripe processes our payments reliably and the uptime has been nearly perfect over two years. However, our chargeback rate has been a persistent problem and the dispute resolution process is deeply frustrating. Stripe provides limited visibility into why disputes are lost, the evidence submission interface is clunky, and in our experience the outcomes favour the cardholder regardless of the evidence provided. We have escalated to our account manager three times and each time received a policy explanation rather than any material help. The infrastructure is excellent; the dispute handling is not.',
    pros: 'Payment reliability and uptime are genuinely excellent. API quality is the best in the industry. Global currency support is seamless.',
    cons: 'Chargeback dispute process has poor visibility and seemingly unfavourable outcomes. Evidence submission interface is cumbersome. Account management is unhelpful for systemic issues.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 5, reliability: 5, wouldWorkAgain: false },
    timestamp: new Date('2026-04-22').toISOString(),
    reviewerHash: 'anon_s9u7w5y3',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@str-05',
    upvotes: 61,
    isVerified: true,
  },

  // ── Notion ────────────────────────────────────────────────────────────────
  {
    id: 'not-01',
    company: 'Notion',
    category: 'Productivity / Collaboration',
    rating: calcRating({ paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'We replaced five tools with Notion and have not looked back',
    content: 'Our team of 45 was previously using Confluence for docs, Trello for project tracking, Airtable for databases, Google Docs for collaborative writing, and a shared folder for reference material. Notion replaced all of them within three months. The flexibility of the block model means the same tool serves every use case, and the permission system is granular enough for enterprise needs. The real-time collaboration is smooth and the template library accelerated our initial setup significantly. For a knowledge-work team of our size, Notion is the right choice.',
    pros: 'One tool replaces five. Block model is flexible enough for any use case. Real-time collaboration is smooth and reliable.',
    cons: 'Performance degrades on very large databases. Mobile app is noticeably slower than the web version. Bulk export options are limited.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-03-05').toISOString(),
    reviewerHash: 'anon_t0v8x6z4',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@not-01',
    upvotes: 51,
    isVerified: true,
  },
  {
    id: 'not-02',
    company: 'Notion',
    category: 'Productivity / Collaboration',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 3, reliability: 3, wouldWorkAgain: false }),
    title: 'Great concept, let down by offline mode that still does not work in 2025',
    content: 'Notion is the tool I want to love and cannot quite bring myself to rely on. The design philosophy is right, the UX is beautiful, and the flexibility is unmatched in the category. But offline mode is broken in a way that affects my team every week. Engineers travelling to client sites lose access to critical documentation because the sync is unreliable and cached content is not reliably available. We have raised this with Notion support four times and received the same template response pointing to a help article. For a productivity tool, unreliable offline access is a fundamental problem.',
    pros: 'Beautiful UX with a thoughtful block-based model. Excellent template library. API is genuinely useful for automation.',
    cons: 'Offline mode is unreliable and has been reported as broken for years. Support responses to known issues are dismissive. Performance on large pages is slow.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 3, reliability: 3, wouldWorkAgain: false },
    timestamp: new Date('2025-07-16').toISOString(),
    reviewerHash: 'anon_u1w9y7a5',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@not-02',
    upvotes: 78,
    isVerified: true,
  },
  {
    id: 'not-03',
    company: 'Notion',
    category: 'Productivity / Collaboration',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true }),
    title: 'Template marketplace partnership drove real installs for our product',
    content: 'We built a Notion template bundle for product managers and listed it in the Notion marketplace. The partnership team was helpful in the initial listing process and the distribution from the marketplace has been meaningful, we have had several thousand template installs that converted to our SaaS product at a measurable rate. Revenue share terms are transparent and payments have been accurate. The main friction has been update velocity, when Notion updates their API or block types, our templates break and the notification window for partner updates is too short.',
    pros: 'Marketplace distribution is real and converts. Partner team is accessible for listing support. Revenue share terms are clear.',
    cons: 'API update notification window is too short for template maintenance. Template breakages from platform updates create user support burden. Marketplace search ranking is opaque.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2025-10-29').toISOString(),
    reviewerHash: 'anon_v2x0z8b6',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@not-03',
    upvotes: 26,
    isVerified: true,
  },
  {
    id: 'not-04',
    company: 'Notion',
    category: 'Productivity / Collaboration',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 5, wouldWorkAgain: false }),
    title: 'Engineering velocity has slowed and internal roadmap communication is poor',
    content: 'I worked at Notion for two years as a senior software engineer and left disappointed by the direction. The engineering foundations are genuinely solid and the infrastructure reliability is excellent, uptime is a point of pride internally. What changed during my tenure was the pace of product shipping and the quality of communication about where we were going. Roadmap discussions became increasingly circular, and it felt like the leadership team was uncertain about the next phase of growth after the initial product-market fit phase. Compensation was good and colleagues were talented, but I left wanting more clarity on purpose.',
    pros: 'Strong infrastructure and reliability engineering culture. Talented colleagues with high standards. Competitive compensation.',
    cons: 'Product roadmap communication became opaque during my tenure. Engineering velocity slowed significantly. Leadership uncertainty about growth strategy was palpable.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 5, wouldWorkAgain: false },
    timestamp: new Date('2026-02-07').toISOString(),
    reviewerHash: 'anon_w3y1a9c7',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@not-04',
    upvotes: 43,
    isVerified: true,
  },
  {
    id: 'not-05',
    company: 'Notion',
    category: 'Productivity / Collaboration',
    rating: calcRating({ paymentContracts: 3, communication: 3, deliveryQuality: 2, reliability: 4, wouldWorkAgain: true }),
    title: 'Excellent for documentation and wikis, inadequate for large structured databases',
    content: 'Our operations team relies on Notion for all internal documentation and it works well for that purpose. Where we have run into problems is using it as a data store for larger datasets, anything over 10,000 rows in a database becomes noticeably slow and filter operations regularly time out. We initially tried to use Notion as a lightweight CRM alternative but had to abandon the effort after performance became unusable at scale. The Notion team has acknowledged the performance issue and indicated it is being addressed, but we have been waiting for a resolution for over a year.',
    pros: 'Excellent wiki and documentation experience. Good permission controls for enterprise use. Real-time editing is reliable.',
    cons: 'Large database performance is unacceptable, over 10k rows is unusable. Filter operations on large tables regularly time out. Progress on performance improvements is slow.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 3, deliveryQuality: 2, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2026-05-01').toISOString(),
    reviewerHash: 'anon_x4z2b0d8',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@not-05',
    upvotes: 37,
    isVerified: true,
  },

  // ── Figma ─────────────────────────────────────────────────────────────────
  {
    id: 'fig-01',
    company: 'Figma',
    category: 'Design / Collaboration',
    rating: calcRating({ paymentContracts: 5, communication: 5, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'Figma transformed how our design and engineering teams collaborate',
    content: 'Before Figma, our design process was a constant battle of file versions, Sketch exports, and miscommunication between designers and engineers. Figma eliminated all of it. The shared source of truth, real-time collaboration, and the developer handoff tools have materially reduced our time from design to implementation. Onboarding the entire team took less than a week. The auto-layout and component variant features have also significantly reduced the time our designers spend maintaining design systems. For any product team, this is table stakes.',
    pros: 'Eliminates version confusion between design and engineering. Developer handoff is genuinely excellent. Component variants dramatically reduce design system maintenance time.',
    cons: 'Large files with many components can become slow in the browser. Some advanced prototyping requires workarounds. Offline access is limited.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 5, communication: 5, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2025-02-18').toISOString(),
    reviewerHash: 'anon_y5a3c1e9',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@fig-01',
    upvotes: 76,
    isVerified: true,
  },
  {
    id: 'fig-02',
    company: 'Figma',
    category: 'Design / Collaboration',
    rating: calcRating({ paymentContracts: 5, communication: 2, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'Plugin review process is inconsistent and communication is non-existent',
    content: 'We built and submitted a productivity plugin for the Figma community. The plugin itself took four weeks to develop. The review process took six months, required three rounds of undocumented changes, and we received no proactive communication from the review team at any stage, we had to follow up every two weeks to get any update at all. Payment terms for the community programme are clear and were honoured. But the review experience was demoralising enough that we will not submit another plugin. The platform is excellent; the developer relations are not.',
    pros: 'Plugin platform itself is well-documented and capable. Payment terms are clear and were honoured. The end user product is genuinely loved by designers.',
    cons: 'Review process timelines are unpredictable and communication is essentially non-existent. Review criteria are not fully documented. Multiple undocumented requirements emerged only after we submitted.',
    relationshipType: 'Vendor',
    categoryRatings: { paymentContracts: 5, communication: 2, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-06-10').toISOString(),
    reviewerHash: 'anon_z6b4d2f0',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@fig-02',
    upvotes: 64,
    isVerified: true,
  },
  {
    id: 'fig-03',
    company: 'Figma',
    category: 'Design / Collaboration',
    rating: calcRating({ paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true }),
    title: 'Community partnership was well-structured with genuine distribution upside',
    content: 'We partnered with Figma to co-promote a design resource library targeting product teams. The partnership team was organised and clearly understood what a successful co-marketing campaign requires. Our resource was featured in their design community newsletter to roughly 400,000 subscribers and generated meaningful inbound interest. The legal process for the partnership agreement was straightforward and payment terms were reasonable. One area of friction was the timeline, the partnership team\'s internal approval process added three weeks to our expected launch date with little explanation.',
    pros: 'Community newsletter distribution is significant and converts well. Partnership team is professional and organised. Commercial terms are reasonable.',
    cons: 'Internal approval timeline added unexpected delays. Communication about internal review stages was incomplete. Co-marketing asset requirements were not fully specified upfront.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2025-09-25').toISOString(),
    reviewerHash: 'anon_a7c5e3g1',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@fig-03',
    upvotes: 31,
    isVerified: true,
  },
  {
    id: 'fig-04',
    company: 'Figma',
    category: 'Design / Collaboration',
    rating: calcRating({ paymentContracts: 3, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'Adobe acquisition shadow hangs over every product decision',
    content: 'I was a senior product designer at Figma when the Adobe acquisition was announced and left eight months later. The period of regulatory uncertainty was genuinely stressful, nobody at the company could speak clearly about the roadmap and several features were visibly deprioritised while the deal was under review. When the acquisition ultimately failed, the leadership response was positive but the product team had lost meaningful momentum. The product quality and internal tools remain excellent. But the acquisition process revealed how dependent the product roadmap had become on the assumption of external resources that never arrived.',
    pros: 'Product quality is genuinely excellent and the design culture is strong. Engineering standards are high. The team remained largely intact through the uncertainty.',
    cons: 'Product roadmap was visibly affected by acquisition uncertainty for over a year. Transparency from leadership during the regulatory process was insufficient. Several planned features were deprioritised indefinitely.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 3, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2026-01-08').toISOString(),
    reviewerHash: 'anon_b8d6f4h2',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@fig-04',
    upvotes: 88,
    isVerified: true,
  },
  {
    id: 'fig-05',
    company: 'Figma',
    category: 'Design / Collaboration',
    rating: calcRating({ paymentContracts: 5, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'FigJam alone is worth the subscription for distributed teams',
    content: 'We run quarterly planning sessions, product discovery workshops, and retrospectives entirely in FigJam, and it has become the connective tissue between our distributed product and engineering teams. The facilitation features, voting, timer, sections, are exactly what you need for structured workshops without the overhead of more complex platforms. The integration with Figma design files means design artefacts are immediately available in the planning context. Billing has been straightforward and pricing has not changed since we signed up eighteen months ago.',
    pros: 'FigJam is exceptional for distributed workshops and planning. Deep integration with Figma design files. Billing has been transparent and consistent.',
    cons: 'FigJam can become slow with many participants and complex boards. Some facilitation features that exist in competitors are still absent.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 5, communication: 4, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2026-04-30').toISOString(),
    reviewerHash: 'anon_c9e7g5i3',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@fig-05',
    upvotes: 42,
    isVerified: true,
  },

  // ── Slack ─────────────────────────────────────────────────────────────────
  {
    id: 'slk-01',
    company: 'Slack',
    category: 'Business Communication',
    rating: calcRating({ paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false }),
    title: 'The always-on culture Slack enables is actively damaging our team\'s productivity',
    content: 'We moved to Slack from email three years ago and I am genuinely uncertain whether it was the right decision. The product works well, search, integrations, and channel structure are all genuinely good. The problem is the culture it creates. Our team average is 4.2 context switches per hour attributed to Slack activity, and the expectation of rapid response has made sustained deep work impossible for many roles. We have tried channel norms and notification policies but they require constant enforcement. The DM-first culture that Slack incentivises is a productivity problem that no configuration can fully solve.',
    pros: 'Channel structure scales well for large teams. Integration library is unmatched. Search works well for recent content.',
    cons: 'Creates an always-on expectation that undermines deep work. DM culture is difficult to control at scale. Channel sprawl requires significant governance to manage.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-01-13').toISOString(),
    reviewerHash: 'anon_d0f8h6j4',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@slk-01',
    upvotes: 92,
    isVerified: true,
  },
  {
    id: 'slk-02',
    company: 'Slack',
    category: 'Business Communication',
    rating: calcRating({ paymentContracts: 2, communication: 3, deliveryQuality: 3, reliability: 3, wouldWorkAgain: false }),
    title: 'Post-Salesforce pricing increases are extractive, 40% in two years',
    content: 'Our Slack spend has increased by 40% over the past two years with no material improvement in the product. The Pro plan jump to Business+ added features we did not need to access features we already had. The renewal process involves a tight window, and when we tried to reduce our seat count to reflect actual headcount, the process was deliberately cumbersome. The product itself is fine, it works, it integrates, people use it. But I would not characterise our continued use as satisfaction. We are using Slack because switching costs are high, not because we are happy customers.',
    pros: 'The product itself is functional and reliable. Integrations cover every tool in our stack. Employee familiarity means zero training cost.',
    cons: 'Pricing has increased 40% in two years with no feature justification. Seat reduction process is deliberately difficult. Renewal window is too short for proper vendor comparison.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 2, communication: 3, deliveryQuality: 3, reliability: 3, wouldWorkAgain: false },
    timestamp: new Date('2025-05-27').toISOString(),
    reviewerHash: 'anon_e1g9i7k5',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@slk-02',
    upvotes: 113,
    isVerified: true,
  },
  {
    id: 'slk-03',
    company: 'Slack',
    category: 'Business Communication',
    rating: calcRating({ paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true }),
    title: 'App directory partnership was functional but slow, worth it for distribution',
    content: 'We listed our project management integration on the Slack App Directory and the distribution has been real. Monthly installs from the directory represent about 15% of our total new user acquisition. The partnership team was reasonable to work with, not exceptional, but not obstructive either. The listing review process took longer than the published timeline, and requirements were not fully documented, but the partner team was responsive when we escalated. The revenue share model is fair and payments have been accurate. I would maintain the partnership but would not count on Slack being a strategic channel.',
    pros: 'Directory distribution is real and represents meaningful acquisition. Revenue share terms are fair. Partner team responds to escalations.',
    cons: 'Listing review timeline is longer than published and requirements are not fully documented. Partner team is not proactively helpful, reactive only. Integration breakages from Slack API changes are common.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2025-09-19').toISOString(),
    reviewerHash: 'anon_f2h0j8l6',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@slk-03',
    upvotes: 28,
    isVerified: true,
  },
  {
    id: 'slk-04',
    company: 'Slack',
    category: 'Business Communication',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 2, reliability: 5, wouldWorkAgain: false }),
    title: 'Culture hollowed out by Salesforce reorgs, I barely recognise the company',
    content: 'I was at Slack for four years, including through the Salesforce acquisition. The first year post-acquisition was manageable, the stated commitment to preserving Slack culture was credible and leadership seemed to mean it. By the second year, the reorgs started. I had four managers in eighteen months. The product roadmap became a Salesforce strategic document rather than a Slack product vision. Engineering velocity dropped as the organisation prioritised Salesforce integration over independent product development. Compensation remained good and the infrastructure is still world-class, but the original energy that made Slack a special place to work is gone.',
    pros: 'Compensation remained competitive throughout. Engineering infrastructure quality is high. Some original colleagues remain who maintain the original culture.',
    cons: 'Four reorgs in eighteen months made planning impossible. Product strategy has been subordinated to Salesforce integration priorities. Original culture has been largely lost.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 2, reliability: 5, wouldWorkAgain: false },
    timestamp: new Date('2026-01-04').toISOString(),
    reviewerHash: 'anon_g3i1k9m7',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@slk-04',
    upvotes: 67,
    isVerified: true,
  },
  {
    id: 'slk-05',
    company: 'Slack',
    category: 'Business Communication',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 3, reliability: 4, wouldWorkAgain: true }),
    title: 'Still the best async communication tool for fully remote teams, when used with discipline',
    content: 'I have managed fully remote teams using Slack for five years and the platform remains the best option in its category for async communication at scale, provided you invest in building explicit norms around its use. The channel structure, thread model, and workflow automation together create a genuinely powerful async workplace. The problems people attribute to Slack are largely cultural problems that would exist in email too. We run explicit "office hours" and response time norms, treat most messages as async by default, and our team productivity has not suffered. The tool is not the problem; the habits are.',
    pros: 'Best async communication platform for distributed teams when used with discipline. Workflow automation reduces manual overhead. Thread model keeps conversations organised.',
    cons: 'Requires explicit cultural investment to prevent always-on expectations. Message search quality degrades for anything older than six months. Pricing increases have outpaced value delivered.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 3, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2026-04-11').toISOString(),
    reviewerHash: 'anon_h4j2l0n8',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@slk-05',
    upvotes: 55,
    isVerified: true,
  },

  // ── Atlassian ─────────────────────────────────────────────────────────────
  {
    id: 'atl-01',
    company: 'Atlassian',
    category: 'Developer Tools / Project Management',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'Jira is the industry standard for a reason, support is a community forum maze',
    content: 'Our engineering organisation of 80 runs entirely on Jira and Confluence and the products themselves are genuinely capable. Sprint management, backlog grooming, and roadmap visibility are all handled well. But the moment something goes wrong you discover that Atlassian customer support is designed to prevent you from reaching a human engineer. We had a critical Jira Data Center licensing issue that took three weeks and five escalations to resolve. The community forum system treats every issue as a documentation problem until it clearly cannot. For a tool this central to engineering operations, the support model is not fit for enterprise use.',
    pros: 'Jira is the industry standard for sprint and backlog management. Confluence is excellent institutional memory. Large talent pool already knows the tools.',
    cons: 'Customer support model is a community forum maze that delays real help by days. Licensing model penalises headcount growth. Jira is over-engineered for teams under 20 people.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-02-28').toISOString(),
    reviewerHash: 'anon_i5k3m1o9',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@atl-01',
    upvotes: 84,
    isVerified: true,
  },
  {
    id: 'atl-02',
    company: 'Atlassian',
    category: 'Developer Tools / Project Management',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 3, wouldWorkAgain: false }),
    title: 'Marketplace partner support team has zero continuity, three account managers in a year',
    content: 'We are a Marketplace app vendor with several thousand installs. In twelve months we have been assigned three different partner support contacts, none of whom had read our account history before their first call. Our last two support tickets sat open for six weeks each with no meaningful progress. Revenue share from the Marketplace is fair when it flows and the commercial terms are transparent. But Atlassian clearly treats small-to-medium Marketplace vendors as low priority, and the lack of continuity in the partner team creates a perpetual restart in every engagement.',
    pros: 'Marketplace gives access to a large installed customer base. Revenue share mechanics are clearly documented in the contract.',
    cons: 'Partner support team has near-zero continuity due to turnover. Ticket resolution times are consistently longer than the published SLA. Escalation to anyone with decision authority is nearly impossible.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 3, wouldWorkAgain: false },
    timestamp: new Date('2025-06-18').toISOString(),
    reviewerHash: 'anon_j6l4n2p0',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@atl-02',
    upvotes: 57,
    isVerified: true,
  },
  {
    id: 'atl-03',
    company: 'Atlassian',
    category: 'Developer Tools / Project Management',
    rating: calcRating({ paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false }),
    title: 'Critical outage, 11-hour first response on Premium tier, unacceptable',
    content: 'We experienced a Jira Cloud outage affecting our entire 70-person engineering team during an active sprint. We are on the Premium tier, which advertises prioritised support. The initial response from support was a community article link. It took eleven hours to speak with an actual Atlassian engineer and a further fourteen hours for full resolution. Post-incident communication was minimal and no SLA credit was proactively offered. For a project management tool that sits at the centre of engineering delivery, an eleven-hour first response is not a Premium tier standard.',
    pros: 'The product recovered fully with no data loss. Status page was eventually updated with accurate information.',
    cons: 'First response during a critical outage was 11 hours on a paid Premium tier. Post-incident review was superficial and no SLA credit was offered proactively. Escalation process is obscure.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 2, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-10-11').toISOString(),
    reviewerHash: 'anon_k7m5o3q1',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@atl-03',
    upvotes: 101,
    isVerified: true,
  },
  {
    id: 'atl-04',
    company: 'Atlassian',
    category: 'Developer Tools / Project Management',
    rating: calcRating({ paymentContracts: 3, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true }),
    title: 'Confluence as institutional memory is genuinely irreplaceable for our engineering org',
    content: 'We have used Confluence for six years and despite the well-documented frustrations with Atlassian support, I would not replace it as our primary engineering wiki. The structured page hierarchy, the integration with Jira for linking decisions to tickets, and the search functionality are all genuinely good. Our engineering runbooks, architecture decision records, and onboarding documentation all live in Confluence and the quality of that knowledge base has materially reduced onboarding time for new engineers. The pricing is reasonable for the value delivered at our scale.',
    pros: 'Confluence page hierarchy is excellent for structured engineering documentation. Jira integration for linking decisions to tickets is genuinely useful. Search quality is good for structured content.',
    cons: 'Rich media embedding is slow to load on older pages. The editor has changed multiple times and not always for the better. Customer support remains a weak point even for paying customers.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2026-02-14').toISOString(),
    reviewerHash: 'anon_l8n6p4r2',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@atl-04',
    upvotes: 38,
    isVerified: true,
  },
  {
    id: 'atl-05',
    company: 'Atlassian',
    category: 'Developer Tools / Project Management',
    rating: calcRating({ paymentContracts: 4, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'World-class engineers, increasingly opaque leadership on strategy',
    content: 'I spent three years at Atlassian as a staff engineer and the technical environment is genuinely one of the best I have encountered. The engineering standards are high, the internal infrastructure is sophisticated, and the teams are staffed with people who take quality seriously. What changed during my tenure was leadership communication. Strategy conversations that had previously been open and detailed became increasingly high-level and abstract. Decisions about product direction were made above team-lead level and communicated as outcomes rather than rationale. I left with respect for the team and uncertainty about the direction.',
    pros: 'Engineering standards and infrastructure are world-class. Strong culture of technical ownership. Compensation is competitive for the market.',
    cons: 'Leadership communication on strategy became less transparent over time. Decision rationale is increasingly withheld from engineering teams. Reorg frequency has increased without clear benefit.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 4, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2026-05-03').toISOString(),
    reviewerHash: 'anon_m9o7q5s3',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@atl-05',
    upvotes: 49,
    isVerified: true,
  },

  // ── Zoom ──────────────────────────────────────────────────────────────────
  {
    id: 'zm-01',
    company: 'Zoom',
    category: 'Video Conferencing',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 5, reliability: 5, wouldWorkAgain: true }),
    title: 'Reliability is genuinely best-in-class, nothing else comes close for call quality',
    content: 'We run all external client meetings on Zoom and have done so for three years. In that time I can count the number of technical call issues on one hand. The audio and video quality across connection types, including mobile and degraded networks, is consistently better than every competitor we have tested. The waiting room and breakout room features work reliably for our managed customer meetings. Our renewal pricing was higher than the previous year but the account manager was straightforward about the increase and negotiation was possible.',
    pros: 'Audio and video quality are best-in-class across connection types. Breakout rooms and waiting rooms are reliable. Client familiarity means zero friction for external meetings.',
    cons: 'Pricing has increased materially since 2020 without equivalent feature additions. AI companion and advanced features require additional paid tiers. Recording management is still cumbersome.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 5, reliability: 5, wouldWorkAgain: true },
    timestamp: new Date('2025-03-21').toISOString(),
    reviewerHash: 'anon_n0p8r6t4',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@zm-01',
    upvotes: 45,
    isVerified: true,
  },
  {
    id: 'zm-02',
    company: 'Zoom',
    category: 'Video Conferencing',
    rating: calcRating({ paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 5, wouldWorkAgain: false }),
    title: 'Reselling Zoom is straightforward, the margin is too thin to be a real business',
    content: 'We resell Zoom as part of a unified communications package to SMB clients. The product sells itself, every prospect already knows and trusts the brand. But the partner economics make it very difficult to build a sustainable practice around Zoom. Standard licence margin is in the 5-8% range, which does not cover the cost of sales and support overhead at our volume. Worse, the Zoom direct team has quoted below our resale cost on three accounts in the past year. When we raised this with our partner manager, the response was sympathetic but there was no mechanism to protect our accounts.',
    pros: 'Product is easy to sell, universal brand recognition eliminates the awareness problem. Renewals are largely automatic. The product is reliable so support tickets are rare.',
    cons: 'Margin on standard licences is 5-8% before support overhead. Direct team actively undercuts partners with no consequences. Partner programme investment in tools and enablement is minimal.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 5, wouldWorkAgain: false },
    timestamp: new Date('2025-07-04').toISOString(),
    reviewerHash: 'anon_o1q9s7u5',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@zm-02',
    upvotes: 33,
    isVerified: true,
  },
  {
    id: 'zm-03',
    company: 'Zoom',
    category: 'Video Conferencing',
    rating: calcRating({ paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false }),
    title: 'Post-pandemic pricing strategy is extractive, paying more for the same product',
    content: 'Zoom\'s pricing in 2025 bears no resemblance to what we originally signed up for. Features that were bundled in our 2021 plan are now in separate paid tiers. The AI companion requires an upgrade. The advanced analytics we used for measuring meeting effectiveness were moved to Business Plus. Our total spend has increased 60% over four years and I cannot point to a single material product improvement in that time. The product itself remains reliable and functional, it just does not cost what it once did, and the value-to-price ratio has deteriorated significantly.',
    pros: 'Reliability and call quality remain excellent. Universal client familiarity. Mobile app is reliable across poor connections.',
    cons: 'Pricing has increased 60% over four years with no material product improvements. Features have been unbundled into higher tiers. Renewal process is opaque about what has changed.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-10-17').toISOString(),
    reviewerHash: 'anon_p2r0t8v6',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@zm-03',
    upvotes: 76,
    isVerified: true,
  },
  {
    id: 'zm-04',
    company: 'Zoom',
    category: 'Video Conferencing',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 4, reliability: 5, wouldWorkAgain: true }),
    title: 'Webinar features are genuinely excellent for virtual events at scale',
    content: 'We run a quarterly virtual conference with 2,000 to 4,000 attendees using Zoom Webinars and the feature set for large-scale events is genuinely impressive. Q&A management, polling, co-panellist management, and the backstage coordination features all work reliably under load. We have not had a single webinar failure in twelve events. The support team for enterprise events is proactive and we have a named support contact for event day. Pricing for large-scale webinar licences is significant but the reliability record justifies it.',
    pros: 'Webinar feature set is genuinely excellent for large-scale virtual events. Named support contact for enterprise events is proactive. Zero failures across twelve large events.',
    cons: 'Webinar licence pricing is significant and increases with attendee count. Post-event analytics could be more detailed. Recording management and hosting remain cumbersome.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 4, reliability: 5, wouldWorkAgain: true },
    timestamp: new Date('2026-01-29').toISOString(),
    reviewerHash: 'anon_q3s1u9w7',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@zm-04',
    upvotes: 39,
    isVerified: true,
  },
  {
    id: 'zm-05',
    company: 'Zoom',
    category: 'Video Conferencing',
    rating: calcRating({ paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: true }),
    title: 'Solid culture and infrastructure team, but strategic direction post-pandemic is unclear',
    content: 'I joined Zoom as a senior infrastructure engineer in 2023 and have stayed because the technical environment is genuinely strong. The infrastructure team operates at a scale that is professionally formative, and the reliability standards are embedded deeply in the engineering culture. What is less clear is where the company is going. The pandemic growth created expectations that cannot be sustained and leadership\'s response has been to expand into adjacent products, hardware, phone, AI, without a coherent thesis connecting them. The individual bets may be right, but the strategic narrative explaining why Zoom is the right company to make them is unconvincing.',
    pros: 'Infrastructure engineering is genuinely world-class. Reliability culture is deeply embedded. Compensation is competitive.',
    cons: 'Strategic direction feels uncertain, too many simultaneous product bets without a clear thesis. Leadership communication on company direction is high-level without substance. Growth expectations are unrealistic given market normalisation.',
    relationshipType: 'Employee',
    categoryRatings: { paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 4, wouldWorkAgain: true },
    timestamp: new Date('2026-04-15').toISOString(),
    reviewerHash: 'anon_r4t2v0x8',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@zm-05',
    upvotes: 28,
    isVerified: true,
  },

  // ── DocuSign ──────────────────────────────────────────────────────────────
  {
    id: 'ds-01',
    company: 'DocuSign',
    category: 'Legal / Contract Management',
    rating: calcRating({ paymentContracts: 3, communication: 4, deliveryQuality: 5, reliability: 5, wouldWorkAgain: true }),
    title: 'Audit trail is comprehensive and legally defensible, reliability is near-perfect',
    content: 'We have processed over 8,000 agreements through DocuSign over three years without a single technical failure. The audit trail is the most comprehensive I have seen, timestamp, IP address, geolocation, and the full event sequence for each signature are all recorded and exportable in a legally recognised format. Our legal team considers the DocuSign audit trail more defensible than wet signatures in contract disputes. Customer success is largely reactive rather than proactive, but when we have needed help the response has been competent and timely.',
    pros: 'Near-perfect reliability over three years of production use. Legally defensible audit trail that exceeds wet signature standards. Integration library covers all major CRM and CLM platforms.',
    cons: 'Per-envelope pricing becomes significant at high volume. Customer success is reactive rather than proactive. UI has not meaningfully improved in three years.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 3, communication: 4, deliveryQuality: 5, reliability: 5, wouldWorkAgain: true },
    timestamp: new Date('2025-01-31').toISOString(),
    reviewerHash: 'anon_s5u3w1y9',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@ds-01',
    upvotes: 52,
    isVerified: true,
  },
  {
    id: 'ds-02',
    company: 'DocuSign',
    category: 'Legal / Contract Management',
    rating: calcRating({ paymentContracts: 4, communication: 2, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false }),
    title: 'Procurement was exhausting and responsiveness vanished after contract signing',
    content: 'We contracted DocuSign professional services for a custom integration with our CLM platform. The security review process alone took four months, partly understandable for enterprise, but our questions during that period routinely went unanswered for two to three weeks. Once the contract was signed, the engagement quality dropped significantly. The project lead we had been working with was replaced and the handover was incomplete. The integration works, but it was materially underdocumented and our engineering team has spent considerable time reverse-engineering logic that should have been in the delivery package.',
    pros: 'Payments were processed correctly and on time. Pre-sales scoping sessions were thorough. The underlying technology integrates reliably with our stack.',
    cons: 'Security review timeline was disproportionate to the integration scope. Responsiveness dropped to near-zero after contract execution. Deliverable documentation was insufficient for independent maintenance.',
    relationshipType: 'Vendor',
    categoryRatings: { paymentContracts: 4, communication: 2, deliveryQuality: 3, reliability: 4, wouldWorkAgain: false },
    timestamp: new Date('2025-06-06').toISOString(),
    reviewerHash: 'anon_t6v4x2z0',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@ds-02',
    upvotes: 44,
    isVerified: true,
  },
  {
    id: 'ds-03',
    company: 'DocuSign',
    category: 'Legal / Contract Management',
    rating: calcRating({ paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true }),
    title: 'Revenue share is fair and distribution is real, portal is stuck in 2018',
    content: 'We have maintained a DocuSign integration in the AppCenter for two years. Monthly installs are modest but consistent and the revenue share payments have been accurate every quarter. The partner team is accessible when we need them and the technical documentation is reasonably well-maintained. The main friction is the partner portal itself, it appears to have received no meaningful investment since at least 2018. The UI is dated, several workflow steps require unnecessary manual workarounds, and self-service reporting is limited. The partnership is financially worth maintaining but investing in it as a growth channel would require DocuSign to show they take the portal seriously.',
    pros: 'Revenue share terms are fair and payments are accurate. Partner team is accessible for escalations. Technical documentation is adequate.',
    cons: 'Partner portal UI has not been updated in years, basic workflow issues remain unresolved. Reporting is limited and requires manual exports. Certification requirements increased without advance notice.',
    relationshipType: 'Partner',
    categoryRatings: { paymentContracts: 3, communication: 3, deliveryQuality: 3, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2025-09-13').toISOString(),
    reviewerHash: 'anon_u7w5y3a1',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@ds-03',
    upvotes: 21,
    isVerified: true,
  },
  {
    id: 'ds-04',
    company: 'DocuSign',
    category: 'Legal / Contract Management',
    rating: calcRating({ paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 5, wouldWorkAgain: false }),
    title: 'Per-envelope pricing model actively penalises growth, time to find an alternative',
    content: 'DocuSign\'s reliability is excellent and the legal team loves the audit trail. The problem is the pricing model. Per-envelope pricing made sense when e-signatures were novel and volume was low. In 2025 it is an anchor that penalises growth, as our deal volume has increased, our DocuSign spend has grown in lockstep without any corresponding improvement in functionality. We are now evaluating alternatives that offer flat-fee unlimited envelope models. The product works well and customer success has been helpful when contacted, but the economics have become difficult to justify against alternatives.',
    pros: 'Reliability is near-perfect. Audit trail quality is legally defensible. Customer success is helpful when contacted.',
    cons: 'Per-envelope pricing penalises growth and becomes very expensive at high volume. Pricing model has not evolved despite competitive pressure. Flat-fee alternatives now offer comparable reliability.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 2, communication: 3, deliveryQuality: 4, reliability: 5, wouldWorkAgain: false },
    timestamp: new Date('2025-12-28').toISOString(),
    reviewerHash: 'anon_v8x6z4b2',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@ds-04',
    upvotes: 67,
    isVerified: true,
  },
  {
    id: 'ds-05',
    company: 'DocuSign',
    category: 'Legal / Contract Management',
    rating: calcRating({ paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true }),
    title: 'IAM integration and CLM features are excellent for our legal operations team',
    content: 'We implemented DocuSign CLM to automate our legal operations workflow and the results have been positive. The contract lifecycle management features, intake forms, approval routing, clause library, are well-designed for enterprise legal teams and the integration with Salesforce CRM is solid. The implementation team was knowledgeable and delivered on the agreed timeline. Our one area of concern was reliability during the first three months, we experienced three separate incidents of degraded performance during high-volume periods that were not reflected on the status page. Performance has since stabilised.',
    pros: 'CLM features are well-designed for enterprise legal workflows. Salesforce integration is reliable and well-documented. Implementation team delivered on schedule.',
    cons: 'Experienced three performance degradation incidents in the first three months that were not surfaced on the status page. CLM learning curve is steeper than the pre-sales demo suggests. Customisation requires professional services.',
    relationshipType: 'Client',
    categoryRatings: { paymentContracts: 4, communication: 4, deliveryQuality: 4, reliability: 3, wouldWorkAgain: true },
    timestamp: new Date('2026-04-09').toISOString(),
    reviewerHash: 'anon_w9y7a5c3',
    hcsTopicId: '0.0.9177253',
    hcsTxId: '0.0.9069262@ds-05',
    upvotes: 36,
    isVerified: true,
  },
]

// ── Store singleton ───────────────────────────────────────────────────────────

export interface AppStore {
  reviews: Review[]
  topicId: string | null
  nftTokenId: string | null
  isInitialized: boolean
}

declare global {
  // eslint-disable-next-line no-var
  var __raterStore: AppStore | undefined
}

function getStore(): AppStore {
  if (!global.__raterStore) {
    global.__raterStore = {
      reviews: [...SEED],
      topicId: process.env.HEDERA_TOPIC_ID || null,
      nftTokenId: process.env.HEDERA_NFT_TOKEN_ID || null,
      isInitialized: false,
    }
  }
  return global.__raterStore
}

export function getReviews(): Review[] {
  return getStore().reviews
}

export function addReview(review: Review): void {
  getStore().reviews.unshift(review)
}

export function getTopicId(): string | null {
  return getStore().topicId
}

export function setTopicId(id: string): void {
  getStore().topicId = id
}

export function getNftTokenId(): string | null {
  return getStore().nftTokenId
}

export function setNftTokenId(id: string): void {
  getStore().nftTokenId = id
}

export function setInitialized(v: boolean): void {
  getStore().isInitialized = v
}

export function isInitialized(): boolean {
  return getStore().isInitialized
}
